In [1]:
import pandas as pd
import json

Helping Functions

In [2]:
def split_after(my_list,separator):    
    for i,s in enumerate(my_list):
        if separator in s:
            my_list[i] = s.split(separator,1)[1] 
        
def split_before(my_list,separator):    
    for i,s in enumerate(my_list):
        if separator in s:
            my_list[i] = s.split(separator,1)[0]
        
def remove_character(my_list,to_rem):
    for i,s in enumerate(my_list):
        if to_rem in s:
            my_list[i] = s.replace(to_rem,'')

Fill missing values in the mention coloumn with 'No mention'

In [3]:
df = pd.read_csv('elon.csv')
df=df.drop('Unnamed: 0', axis=1)

In [4]:
#clean mention coloumn
df['Mention']=df['Mention'].fillna('No mention')

In [5]:
df

,Date,Tweet,Likes,Retweet,Reply,Mention
0,2022-12-10 23:22:58+00:00,@Twitter And many other features to come!,24493,1668,2587,"[User(username='Twitter', id=783214, displayna..."
1,2022-12-10 20:01:11+00:00,https://t.co/80DdvpsNjM,616866,65419,19446,No mention
2,2022-12-10 19:56:59+00:00,Twitter is both a social media company and a c...,659791,91219,34773,No mention
3,2022-12-10 19:29:34+00:00,@elizableu Looks like Yoel is arguing in favor...,59350,14687,5821,"[User(username='elizableu', id=121039816487802..."
4,2022-12-10 19:21:31+00:00,@elizableu This explains a lot,90564,6867,1611,"[User(username='elizableu', id=121039816487802..."
...,...,...,...,...,...,...
15630,2018-01-07 03:00:48+00:00,@mhmtkcn Near 405,1151,28,47,"[User(username='mhmtkcn', id=14138617886601584..."
15631,2018-01-05 00:30:15+00:00,https://t.co/3k71xzDIP1,26042,3492,609,No mention
15632,2018-01-05 00:30:00+00:00,Falcon Heavy goes vertical https://t.co/uG1k0W...,80725,13908,1976,No mention
15633,2018-01-03 08:22:31+00:00,Using a neural net to detect rain using camera...,16471,2170,655,No mention
15634,2018-01-03 05:38:16+00:00,Come work at the biggest &amp; most advanced f...,50101,6747,3028,No mention

Now we want to clean the Mention column in order to have just the username of the mentioned user

In [6]:
mention_arr = df['Mention'].to_numpy()

In [7]:
split_before(mention_arr,',')

In [8]:
split_after(mention_arr,'=')

In [9]:
mention_arr[0]

"'Twitter'"

In [10]:
remove_character(mention_arr,'\'')

Adding the @ symbol to keep the shape of the followers and following

In [11]:
for i,s in enumerate(mention_arr):
    if s != 'No mention':
        mention_arr[i] ="@"+s

In [12]:
df=df.drop('Mention', axis=1)

In [13]:
df['Mention'] = mention_arr.tolist()

In [14]:
df

,Date,Tweet,Likes,Retweet,Reply,Mention
0,2022-12-10 23:22:58+00:00,@Twitter And many other features to come!,24493,1668,2587,@Twitter
1,2022-12-10 20:01:11+00:00,https://t.co/80DdvpsNjM,616866,65419,19446,No mention
2,2022-12-10 19:56:59+00:00,Twitter is both a social media company and a c...,659791,91219,34773,No mention
3,2022-12-10 19:29:34+00:00,@elizableu Looks like Yoel is arguing in favor...,59350,14687,5821,@elizableu
4,2022-12-10 19:21:31+00:00,@elizableu This explains a lot,90564,6867,1611,@elizableu
...,...,...,...,...,...,...
15630,2018-01-07 03:00:48+00:00,@mhmtkcn Near 405,1151,28,47,@mhmtkcn
15631,2018-01-05 00:30:15+00:00,https://t.co/3k71xzDIP1,26042,3492,609,No mention
15632,2018-01-05 00:30:00+00:00,Falcon Heavy goes vertical https://t.co/uG1k0W...,80725,13908,1976,No mention
15633,2018-01-03 08:22:31+00:00,Using a neural net to detect rain using camera...,16471,2170,655,No mention
15634,2018-01-03 05:38:16+00:00,Come work at the biggest &amp; most advanced f...,50101,6747,3028,No mention

In [15]:
df=df.drop('Date', axis=1)

In [16]:
df.to_csv('elon-cleaned.csv')

Clean followers and following

The username of the users is place between brackest, hence the string was split accordingly

In [53]:
followers =[]
with open("followers_raw","r") as fp:
    followers=json.load(fp)

In [54]:
len(followers)

33015

In [56]:
split_after(followers,'(')

In [57]:
remove_character(followers,')')

In [46]:
with open("followers_cleaned","w") as fp:
    json.dump(followers,fp)

In [51]:
following =[]
with open("following_raw","r") as fp:
    following=json.load(fp)

In [52]:
len(following)

151

In [64]:
split_after(following,'(')

In [65]:
remove_character(following,')')

In [66]:
following[0]

'@neontaster'

In [67]:
with open("following_cleaned","w") as fp:
    json.dump(following,fp)