In [1]:
import chess
import chess.pgn
import pandas as pd
import numpy as np

In [2]:
pgn = open("moves.pgn")

Initializing lists to store the name of white, the name of black, the date and result

In [3]:
white = []
black = []
date = []
result = []

Iterate through each game in the PGN file

In [4]:
while True:
    game= chess.pgn.read_game(pgn)
    if game is not None:
        result.append(game.headers['Result'])
        white.append(game.headers['White'])
        black.append(game.headers['Black'])
        date.append(game.headers['Date'])    
    else: 
        break

KeyboardInterrupt:

In [32]:
print(len(white))
print(len(black))
print(len(date))
print(len(result))

4395602
4395602
4395602
4395602

In [15]:
df = pd.DataFrame(list(zip(white,black,result,date)),
                 columns=['WHITE','BLACK','RESULT','DATE'])

Collecting the moves of each game in algebric notation

In [29]:
alg_not = []

In [30]:
while True:
    game= chess.pgn.read_game(pgn)
    if game is not None:
        board = game.board()
        algebric_moves=[]
        for move in game.mainline_moves():
            alg = board.san(move)
            algebric_moves.append(alg)
            board.push(move)
        if not algebric_moves:                #the algebric_moves list is used to check if the are no moves in that game
            alg_not.append(np.nan)
        else:
            alg_not.append(algebric_moves)   
    else: 
        break

error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2976, in parse_san
    return next(move for move in self.generate_castling_moves() if self.is_queenside_castling(move))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2978, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'O-O-O' in r3k2r/1pqbbp2/p1n1pp2/7p/B7/2N1QN2/PP3PPP/2R1R1K1 b - - 1 19
error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2976, in parse_san
    return next(move for move in self.generate_castling_moves() if self.is_queenside_castling(move))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2978, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'O-O-O' in r3k2r/3nbppp/1nppp3/p4PP1/1p1PP3/3PBNN1/PP5P/1K1R3R b k - 0 18

KeyboardInterrupt:

In [31]:
len(alg_not)

3691281

Since the idea is to create a dataframe, the lists are sliced in order to have the same length

In [33]:
a = white[:len(alg_not)]

In [36]:
b = black[:len(alg_not)]

In [37]:
c = result[:len(alg_not)]

In [38]:
d = date[:len(alg_not)]

In [40]:
len(d)

3691281

In [42]:
df2 = pd.DataFrame(list(zip(a,b,c,d,alg_not)),
                 columns=['WHITE','BLACK','RESULT','DATE','MOVES'])

In [44]:
df2

,WHITE,BLACK,RESULT,DATE,MOVES
0,?,?,*,????.??.??,"[e4, c5, Nf3, e6, d4, cxd4, Nxd4, a6, Nc3, d6,..."
1,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN
2,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN
3,"Ritsema, Ronald","Noomen, Jeroen",0-1,????.??.??,"[c4, Nf6, Nc3, e5, Nf3, Nc6, g3, Bb4, Nd5, Bc5..."
4,"Fressinet, Laurent","Argandona Riveiro, Inigo",1-0,????.06.11,"[d4, d5, c4, dxc4, Nf3, a6, e3, e6, Bxc4, Nf6,..."
...,...,...,...,...,...
3691276,"Andersson, S","Andersson, Ka",1/2-1/2,2010.07.07,"[d4, d5, Nf3, Nf6, g3, g6, Bg2, Bg7, O-O, O-O,..."
3691277,"Lyell, M..","Lengyel, Bela",1/2-1/2,2010.07.07,"[e4, e5, f4, exf4, Nf3, Be7, Nc3, Nf6, d4, d5,..."
3691278,"Lyell, M.","Lengyel, Bela",1/2-1/2,2010.07.07,"[e4, e5, f4, exf4, Nf3, Be7, Nc3, Nf6, d4, d5,..."
3691279,"Wahlbom, Magnus","Axelsson, Uno",1-0,2010.07.07,"[e4, e6, d4, d5, Nd2, Nf6, e5, Nfd7, Bd3, c5, ..."
3691280,"Vul, Arkadi Eremeevich","Novik, Ma",1/2-1/2,2010.07.07,"[Nf3, c5, c4, Nf6, Nc3, e6, g3, d5, cxd5, exd5..."

Collecting the elo of the white and black player

In [12]:
w_elo = []
b_elo = []

In [13]:
while True:
    game= chess.pgn.read_game(pgn)
    if game is not None:
        try:
            b_elo.append(game.headers['BlackElo'])
        except:
            b_elo.append(np.nan)
            continue
        try:
            w_elo.append(game.headers['WhiteElo'])
        except:
            w_elo.append(np.nan)
            continue;
    else: 
        break

error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2976, in parse_san
    return next(move for move in self.generate_castling_moves() if self.is_queenside_castling(move))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2978, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'O-O-O' in r3k2r/1pqbbp2/p1n1pp2/7p/B7/2N1QN2/PP3PPP/2R1R1K1 b - - 1 19
error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2976, in parse_san
    return next(move for move in self.generate_castling_moves() if self.is_queenside_castling(move))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 2978, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'O-O-O' in r3k2r/3nbppp/1nppp3/p4PP1/1p1PP3/3PBNN1/PP5P/1K1R3R b k - 0 18
error during pgn parsing
Traceback (most recent call last):
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1685, in read_game
    move = visitor.parse_san(board_stack[-1], token)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\pgn.py", line 1059, in parse_san
    return board.parse_san(san)
  File "C:\Users\miche\anaconda3\lib\site-packages\chess\__init__.py", line 3039, in parse_san
    raise ValueError(f"illegal san: {san!r} in {self.fen()}")
ValueError: illegal san: 'bxc1=N' in 8/6qk/8/5KPp/1Q3p2/4P1P1/1p6/8 b - - 1 69

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 222: character maps to <undefined>

In [14]:
len(w_elo)

3833393

In [16]:
len(df2)

3691281

In [17]:
sliced_w_elo = w_elo[:len(df2)]
sliced_b_elo = b_elo[:len(df2)]

In [18]:
len(sliced_w_elo)

3691281

In [19]:
len(sliced_b_elo)

3691281

In [20]:
df['B_ELO'] = sliced_b_elo

In [21]:
df

,WHITE,BLACK,RESULT,DATE,MOVES,B_ELO
0,?,?,*,????.??.??,"['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4'...",2804
1,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN,2606
2,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN,2606
3,"Ritsema, Ronald","Noomen, Jeroen",0-1,????.??.??,"['c4', 'Nf6', 'Nc3', 'e5', 'Nf3', 'Nc6', 'g3',...",NaN
4,"Fressinet, Laurent","Argandona Riveiro, Inigo",1-0,????.06.11,"['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'a6', 'e3', ...",2382
...,...,...,...,...,...,...
3691276,"Andersson, S","Andersson, Ka",1/2-1/2,2010.07.07,"['d4', 'd5', 'Nf3', 'Nf6', 'g3', 'g6', 'Bg2', ...",2098
3691277,"Lyell, M..","Lengyel, Bela",1/2-1/2,2010.07.07,"['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7', 'Nc3'...",2257
3691278,"Lyell, M.","Lengyel, Bela",1/2-1/2,2010.07.07,"['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7', 'Nc3'...",2257
3691279,"Wahlbom, Magnus","Axelsson, Uno",1-0,2010.07.07,"['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nf6', 'e5', '...",NaN
3691280,"Vul, Arkadi Eremeevich","Novik, Ma",1/2-1/2,2010.07.07,"['Nf3', 'c5', 'c4', 'Nf6', 'Nc3', 'e6', 'g3', ...",2475

In [22]:
df['W_ELO'] = sliced_w_elo

In [23]:
df

,WHITE,BLACK,RESULT,DATE,MOVES,B_ELO,W_ELO
0,?,?,*,????.??.??,"['e4', 'c5', 'Nf3', 'e6', 'd4', 'cxd4', 'Nxd4'...",2804,2666
1,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN,2606,2621
2,"Naroditsky, Daniel","Hansen, Eric",1-0,????.??.??,NaN,2606,2621
3,"Ritsema, Ronald","Noomen, Jeroen",0-1,????.??.??,"['c4', 'Nf6', 'Nc3', 'e5', 'Nf3', 'Nc6', 'g3',...",NaN,2633
4,"Fressinet, Laurent","Argandona Riveiro, Inigo",1-0,????.06.11,"['d4', 'd5', 'c4', 'dxc4', 'Nf3', 'a6', 'e3', ...",2382,2461
...,...,...,...,...,...,...,...
3691276,"Andersson, S","Andersson, Ka",1/2-1/2,2010.07.07,"['d4', 'd5', 'Nf3', 'Nf6', 'g3', 'g6', 'Bg2', ...",2098,2392
3691277,"Lyell, M..","Lengyel, Bela",1/2-1/2,2010.07.07,"['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7', 'Nc3'...",2257,2392
3691278,"Lyell, M.","Lengyel, Bela",1/2-1/2,2010.07.07,"['e4', 'e5', 'f4', 'exf4', 'Nf3', 'Be7', 'Nc3'...",2257,2211
3691279,"Wahlbom, Magnus","Axelsson, Uno",1-0,2010.07.07,"['e4', 'e6', 'd4', 'd5', 'Nd2', 'Nf6', 'e5', '...",NaN,2224
3691280,"Vul, Arkadi Eremeevich","Novik, Ma",1/2-1/2,2010.07.07,"['Nf3', 'c5', 'c4', 'Nf6', 'Nc3', 'e6', 'g3', ...",2475,2394

In [25]:
#df.to_csv('final_chess.csv')